[project]
name = "mm-notify"
version = "0.3.0"
description = "A bot to scrape notices from my child's school website and post to a hass instance"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "requests>=2.32.3",
]
